#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=10

VERIFY_DIR="${SLIVER_VERIFY_DIR:-$HOME/sliver-release-verification}"
mkdir -p "$VERIFY_DIR"
LOG_FILE="$VERIFY_DIR/$(date +%Y%m%d-%H%M%S).log"
exec > >(tee -a "$LOG_FILE") 2>&1

RPM_PATH="${1:-}"
PACKAGE_WAS_INSTALLED=0
TINY_STOPPED=0
TAKEOVER_ACTIVE=0
CONFIG_DIR=""

if command -v rpm >/dev/null 2>&1 && rpm -q sliver >/dev/null 2>&1; then
  PACKAGE_WAS_INSTALLED=1
fi

run_optional() {
  if "$@"; then
    return 0
  fi
  warn "command failed, so record it as a blocker: $*"
  SKIPPED+=("$*")
  return 0
}

rollback() {
  if (( TAKEOVER_ACTIVE )); then
    say "Stopping Sliver and disabling takeover."
    sudo systemctl disable --now sliver-broker.service || true
    systemctl --user disable --now sliver-supervisor.service || true
    sudo systemctl --global disable sliver-supervisor.service || true
    if (( TINY_STOPPED )); then
      sudo systemctl start tiny-dfr.service || true
    fi
    TAKEOVER_ACTIVE=0
  fi
  if [[ -n "$CONFIG_DIR" ]]; then
    rm -rf -- "$CONFIG_DIR"
    CONFIG_DIR=""
  fi
}

on_exit() {
  local status=$?
  if (( status != 0 )); then
    warn "verification stopped with status $status"
    warn "No automatic rollback was attempted. If takeover is active, run:"
    say "sudo systemctl disable --now sliver-broker.service"
    say "systemctl --user disable --now sliver-supervisor.service"
    say "sudo systemctl --global disable sliver-supervisor.service"
    say "sudo systemctl start tiny-dfr.service  # only if it owned the panel before this run"
  fi
  exit "$status"
}
trap on_exit EXIT

expect_silent_success() {
  local label="$1"
  shift
  local stderr_file="$VERIFY_DIR/$label.stderr"
  local stdout
  if ! stdout=$("$@" 2>"$stderr_file"); then
    cat "$stderr_file" >&2
    return 1
  fi
  [[ -z "$stdout" ]] || {
    warn "$label wrote to stdout"
    return 1
  }
  [[ ! -s "$stderr_file" ]] || {
    cat "$stderr_file" >&2
    warn "$label wrote to stderr"
    return 1
  }
}

write_test_config() {
  CONFIG_DIR=$(mktemp -d "${TMPDIR:-/tmp}/sliver-release.XXXXXX")
  cat > "$CONFIG_DIR/valid.lua" <<'LUA'
local sliver = require("sliver.v1")
return {
    api_version = 1,
    render = function(canvas)
        canvas:rectangle(0, 0, 2008, 60, "#000000")
        canvas:text(20, 36, "release verifier", 24, "#ffffff")
    end,
}
LUA
  cat > "$CONFIG_DIR/invalid.lua" <<'LUA'
local sliver = require("sliver.v1")
return {
    api_version = 1,
    render = function()
        error("release verifier failure")
    end,
}
LUA
}

banner "Sliver release verification"

stage "Record the host and hardware"
say "This stage only reads state. It does not stop a daemon or change devices."
step "The accepted real device is an M2 Mac14,7. M1 is not claimed by this release."
printf '  kernel: '; uname -a
printf '  architecture: '; uname -m
if [[ -r /sys/firmware/devicetree/base/model ]]; then
  printf '  device-tree model: '; tr -d '\0' < /sys/firmware/devicetree/base/model; printf '\n'
elif [[ -r /sys/devices/virtual/dmi/id/product_name ]]; then
  printf '  product name: '; cat /sys/devices/virtual/dmi/id/product_name
else
  warn "could not find a host model file"
  SKIPPED+=("host model discovery")
fi
run_optional id sliver
run_optional pgrep -a -f 'tiny-dfr|sliver-broker|sliver-supervisor'
if command -v drm_info >/dev/null 2>&1; then
  step "Save the DRM connector and mode output in the evidence log."
  run_optional drm_info
else
  warn "drm_info is not installed; inspect the DRM connector manually before takeover"
  SKIPPED+=("drm_info hardware inspection")
fi
pause "Review the model, connector, and current owner above. Press Enter to continue."

stage "Build and inspect the Fedora package"
say "Build the RPM outside this verifier, then pass its path as the first argument."
if [[ -z "$RPM_PATH" ]]; then
  step "Run the documented rpmbuild commands from packaging/fedora/INSTALL.md."
  step "The build must run its complete Cargo and package checks before installation."
  read -r -p "Path to the RPM to verify (leave empty to skip package checks): " RPM_PATH
fi
if [[ -n "$RPM_PATH" ]]; then
  [[ -f "$RPM_PATH" ]] || { warn "RPM does not exist: $RPM_PATH"; exit 1; }
  command -v rpm >/dev/null 2>&1 || { warn "rpm is required to inspect the package"; exit 1; }
  rpm -qpl "$RPM_PATH" | tee "$VERIFY_DIR/package-files.txt"
  grep -Fx '/usr/bin/sliver' "$VERIFY_DIR/package-files.txt" >/dev/null
  ! grep -E '/(sliver-edit|sliver-probe|sliver-preview|default\.lua)$' "$VERIFY_DIR/package-files.txt" >/dev/null
else
  warn "package verification was skipped"
  SKIPPED+=("Fedora RPM build and file-list verification")
fi

stage "Install without taking ownership"
if [[ -z "$RPM_PATH" ]]; then
  warn "No RPM was supplied. The install and service checks cannot pass."
  SKIPPED+=("package installation")
else
  step "The RPM must not enable or start Sliver by itself."
  if confirm "Install this RPM with dnf now?"; then
    sudo dnf install -y "$RPM_PATH"
  else
    warn "installation was declined"
    SKIPPED+=("package installation")
  fi
fi
run_optional systemctl is-enabled sliver-broker.service
run_optional systemctl is-active tiny-dfr.service
pause "Confirm that installation did not take over the panel. Press Enter to continue."

stage "Prepare accounts and udev permissions"
step "Run the accepted administrator setup for the packaged broker and user supervisor."
say "The commands below change group membership and enable the restricted pre-login user manager."
if [[ -n "$RPM_PATH" ]]; then
  sudo usermod --append --groups sliver-supervisors "$USER"
  sudo loginctl enable-linger sliver
  sudo udevadm control --reload-rules
  sudo udevadm trigger --subsystem-match=drm
  sudo udevadm trigger --subsystem-match=input
  sudo udevadm trigger --subsystem-match=misc
  sudo udevadm trigger --subsystem-match=backlight
  warn "Log out and back in before enabling the user supervisor so group membership is real."
  pause "After starting a fresh local graphical session, press Enter to continue."
else
  warn "account and udev setup skipped because no package was installed"
  SKIPPED+=("broker account and udev setup")
fi

stage "Capture the pre-takeover owner"
step "Save the owner and service state before changing it."
run_optional systemctl --no-pager status tiny-dfr.service
run_optional pgrep -a -f 'tiny-dfr|sliver-broker'
for device in /dev/dri/card* /dev/input/event* /dev/uinput; do
  [[ -e "$device" ]] && ls -l "$device"
done
run_optional fuser -v /dev/dri/card0
pause "Keep this evidence. It is the rollback reference. Press Enter to continue."

stage "Enable Sliver takeover"
if ! confirm "Stop tiny-dfr and enable Sliver on the real panel?"; then
  warn "takeover was declined; no release evidence can be collected"
  SKIPPED+=("real hardware takeover")
  exit 1
fi
if systemctl is-active --quiet tiny-dfr.service; then
  sudo systemctl stop tiny-dfr.service
  TINY_STOPPED=1
fi
TAKEOVER_ACTIVE=1
sudo systemctl enable --now sliver-broker.service
sudo systemctl --global enable sliver-supervisor.service
systemctl --user enable --now sliver-supervisor.service
systemctl is-active --quiet sliver-broker.service
systemctl --user is-active --quiet sliver-supervisor.service

stage "Run the public CLI against the real services"
write_test_config
step "The following commands exercise help, version, explicit apply, invalid apply, and default reset."
help_output=$(sliver --help)
[[ "$help_output" == "usage: sliver [FILE]" ]] || { warn "unexpected help output"; exit 1; }
version_output=$(sliver --version)
printf '  %s\n' "$version_output"
expect_silent_success explicit-apply sliver "$CONFIG_DIR/valid.lua"
invalid_stderr="$VERIFY_DIR/invalid.stderr"
if sliver "$CONFIG_DIR/invalid.lua" >"$VERIFY_DIR/invalid.stdout" 2>"$invalid_stderr"; then
  warn "invalid live apply unexpectedly succeeded"
  exit 1
fi
[[ -s "$invalid_stderr" ]] || { warn "invalid apply produced no diagnostic"; exit 1; }
expect_silent_success default-reset sliver
rm -rf -- "$CONFIG_DIR"
CONFIG_DIR=""
step "Inspect the saved path and both service journals for source, stage, and error text."
run_optional journalctl --user -u sliver-supervisor.service -n 100 --no-pager
run_optional journalctl -u sliver-broker.service -n 100 --no-pager

stage "Exercise login, handoff, recovery, and cleanup"
say "These checks need a person at the machine. Do not use SSH for the apply test."
step "With the default visible, log into a second local graphical session and switch back and forth."
step "Apply a valid file as the active user, then apply the invalid file and confirm the previous frame remains."
step "Hold Fn/Globe continuously for three seconds, tap a recovery key, and confirm modifier bridging."
step "Log out, confirm the pre-login default returns, then log back in and confirm the saved config commits without a blank interval."
step "Check that a stopped or failed worker leaves no child process and no held synthetic key."
pause "Perform the checks above and press Enter only after reviewing the panel and both journals."
run_optional systemctl --user status sliver-supervisor.service
run_optional systemctl status sliver-broker.service

stage "Exercise suspend, restart, and frame-rate evidence"
step "Restart each infrastructure service once and inspect the handoff and journal output."
sudo systemctl restart sliver-broker.service
systemctl --user restart sliver-supervisor.service
run_optional systemctl status sliver-broker.service
run_optional systemctl --user status sliver-supervisor.service
if confirm "Suspend the machine now, then resume it to verify backlight, touch cancellation, and one fresh frame?"; then
  sudo systemctl suspend
else
  warn "suspend verification was declined"
  SKIPPED+=("suspend and resume")
fi
step "Run the repository's fake-adapter 2008x60 producer test and keep its measured output."
run_optional cargo test --release lua_raw_decoded_frames_hold_native_rate_under_broker_contention -- --nocapture
step "On Mac14,7, repeat the video workload while watching the panel. Record frame misses, input-to-frame delay, and whether latency grows."
pause "Record the real 60 FPS bounded-latency result in the evidence log. Press Enter to continue."

stage "Choose rollback and save the evidence"
say "The evidence log is $LOG_FILE"
run_optional journalctl --user -u sliver-supervisor.service -b --no-pager
run_optional journalctl -u sliver-broker.service -b --no-pager
if confirm "Roll back takeover now and return ownership to tiny-dfr if it owned the panel before this run?"; then
  rollback
else
  say "Leaving Sliver installed but enabled. Roll back later with:"
  say "sudo systemctl disable --now sliver-broker.service"
  say "systemctl --user disable --now sliver-supervisor.service"
  say "sudo systemctl --global disable sliver-supervisor.service"
  say "sudo systemctl start tiny-dfr.service  # only when handing ownership back"
fi

finish
